#!/bin/sh

if [ -z $BASE ]; then
    BASE=`pwd`;
fi

if [ ! -e $BASE/java/RhinoTest.class ]; then
    echo "RhinoTest has not been compiled. Run: javac -cp \$RHINO RhinoTest.java" 1>&2;
    exit 1
fi

if [ -z $RHINO ]; then
    echo "RHINO not set; you need to set RHINO to the location of js.jar" 1>&2;
    exit 1
fi

CLASSPATH=$BASE/java:$RHINO java RhinoTest $1
